export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_MY_ORDER = "GET_MY_ORDER";
export const GET_MY_ORDER_SUCCESS = "GET_MY_ORDER_SUCCESS";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
